package com.atlas.crmapp.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.atlas.crmapp.db.model.ProductCart;
import com.atlas.crmapp.db.model.PushMsg;
import com.atlas.crmapp.db.model.ChatCount;

import com.atlas.crmapp.db.greendao.ProductCartDao;
import com.atlas.crmapp.db.greendao.PushMsgDao;
import com.atlas.crmapp.db.greendao.ChatCountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productCartDaoConfig;
    private final DaoConfig pushMsgDaoConfig;
    private final DaoConfig chatCountDaoConfig;

    private final ProductCartDao productCartDao;
    private final PushMsgDao pushMsgDao;
    private final ChatCountDao chatCountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productCartDaoConfig = daoConfigMap.get(ProductCartDao.class).clone();
        productCartDaoConfig.initIdentityScope(type);

        pushMsgDaoConfig = daoConfigMap.get(PushMsgDao.class).clone();
        pushMsgDaoConfig.initIdentityScope(type);

        chatCountDaoConfig = daoConfigMap.get(ChatCountDao.class).clone();
        chatCountDaoConfig.initIdentityScope(type);

        productCartDao = new ProductCartDao(productCartDaoConfig, this);
        pushMsgDao = new PushMsgDao(pushMsgDaoConfig, this);
        chatCountDao = new ChatCountDao(chatCountDaoConfig, this);

        registerDao(ProductCart.class, productCartDao);
        registerDao(PushMsg.class, pushMsgDao);
        registerDao(ChatCount.class, chatCountDao);
    }
    
    public void clear() {
        productCartDaoConfig.clearIdentityScope();
        pushMsgDaoConfig.clearIdentityScope();
        chatCountDaoConfig.clearIdentityScope();
    }

    public ProductCartDao getProductCartDao() {
        return productCartDao;
    }

    public PushMsgDao getPushMsgDao() {
        return pushMsgDao;
    }

    public ChatCountDao getChatCountDao() {
        return chatCountDao;
    }

}
